#:schema node_modules/wrangler/config-schema.json
name = "idea-lark-r2"
main = "src/index.ts"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "idea-lark-r2"

[observability]
enabled = true
head_sampling_rate = 1 

[vars]
LARK_HOST = "https://open.feishu.cn/open-apis/"
